apiVersion: v1
kind: Service
metadata:
  name: drkiq
  labels:
    app: drkiq
spec:
  ports:
  - name: "8000"
    port: 8000
    targetPort: 8000
  selector:
    app: drkiq
status:
  loadBalancer: {}
