apiVersion: v1
kind: Service
metadata:
    name: "postgres-service"
spec:
  ports:
  - name: "5432"
    protocol: "TCP"
    port: 5432
    targetPort: 5432
  selector:
    db: postgres
status:
  loadBalancer: {}
