apiVersion: v1
kind: Service
metadata:
  name: "redis-service"
spec:
  ports:
  - name: "6379"
    protocol: "TCP"
    port: 6379
    targetPort: 6379
  selector:
    db: redis
status:
  loadBalancer: {}
