apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: redis
  labels:
    db: redis
spec:
  strategy:
    type: Recreate
  replicas: 2
  template:
    metadata:
      labels:
        db: redis
    spec:
      containers:
      - image: redis:3.0.5
        name: redis
        ports:
        - containerPort: 6379
        resources: {}
        volumeMounts:
        - mountPath: /var/lib/redis/data
          name: drkiq-redis
      restartPolicy: Always
      volumes:
      - name: drkiq-redis
        persistentVolumeClaim:
          claimName: drkiq-redis
