apiVersion: v1
kind: Service
metadata:
  name: sidekiq
  labels:
    app: sidekiq
spec:
  clusterIP: None
  ports:
  - name: headless
    port: 55555
    targetPort: 0
  selector:
    app: sidekiq
status:
  loadBalancer: {}
